config/routes.rb
Ccghoard::Application.routes.draw do

  resources :decks
  resources :cards

  authenticated :user do
    root :to => 'cards#index'
  end
  root :to => "cards#index"
  devise_for :users
  resources :users



end

app/models/card.rb
class Card < ActiveRecord::Base
  resourcify
  attr_accessible :cardset, :cardtype, :color, :manacost, :description, :image, :name, :powertoughness, :price

  has_and_belongs_to_many :decks


  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      scoped
    end
  end

  def get_image
    image || 'default.jpg'
  end

  def get_symbols(mana_info)
    #parse the manacost string, look for particular key characters representing the sybmol
    #image in place of the character
    #
    #assuming incoming variable and column value: @card.manacost
    #
    #Syntax Check:
    #card = "(2/U)(2/U)(2/U)"
    #card = "2RB"
    #card = "2(R/U)(R/U)"
    image_array = []
    hybrid_mana = ""
    capture_text = false
    mana_info.split("").each do |symbol|
      image_name = ""
      if symbol == "("
        capture_text = true
        hybrid_mana = ""
      elsif symbol == ")"
        capture_text = false
      else

      end

      if capture_text == true && symbol != "("
        hybrid_mana += symbol
      elsif hybrid_mana != ""
        case hybrid_mana
          #hybrid mana
          when "W/U"
            image_name = "whiteblue.png"
          when "W/B"
            image_name = "whiteblack.png"
          when "U/B"
            image_name = "blueblack.png"
          when "U/R"
            image_name = "bluered.png"
          when "B/R"
            image_name = "blackred.png"
          when "B/G"
            image_name = "blackgreen.png"
          when "R/G"
            image_name = "redgreen.png"
          when "R/W"
            image_name = "redwhite.png"
          when "G/W"
            image_name = "greenwhite.png"
          when "G/U"
            image_name = "greenblue.png"

          #hybrid mana inverse
          when "U/W"
            image_name = "bluewhite.png"
          when "B/W"
            image_name = "blackwhite.png"
          when "B/U"
            image_name = "blackblue.png"
          when "R/U"
            image_name = "redblue.png"
          when "R/B"
            image_name = "redblack.png"
          when "G/B"
            image_name = "greenblack.png"
          when "G/R"
            image_name = "greenred.png"
          when "W/R"
            image_name = "whitered.png"
          when "W/G"
            image_name = "whitegreen.png"
          when "U/G"
            image_name = "bluegreen.png"
          #monocolored hybrid
          when "1/G"
            image_name = "1green.png"
          when "1/U"
            image_name = "1blue.png"
          when "1/R"
            image_name = "1red.png"
          when "1/B"
            image_name = "1black.png"
          when "1/W"
            image_name = "1white.png"
          when "2/G"
            image_name = "2green.png"
          when "2/U"
            image_name = "2blue.png"
          when "2/R"
            image_name = "2red.png"
          when "2/B"
            image_name = "2black.png"
          when "2/W"
            image_name = "2white.png"
          when "3/G"
            image_name = "3green.png"
          when "3/U"
            image_name = "3blue.png"
          when "3/R"
            image_name = "3red.png"
          when "3/B"
            image_name = "3black.png"
          when "3/W"
            image_name = "3white.png"
        end
      else

        #add all checks for every manacost type of every card possible, replace with a image_tag()
        #for the appropriate image of the symbol
        case symbol

          #standard mana types ex. forest, mountain, island, swamp, plain
          when "G"
            image_name = "green.png"
          when "U"
            image_name = "blue.png"
          when "R"
            image_name = "red.png"
          when "B"
            image_name = "black.png"
          when "W"
            image_name = "white.png"

          #colorless mana
          when "0"
            image_name = "0.png"
          when "1"
            image_name = "1.png"
          when "2"
            image_name = "2.png"
          when "3"
            image_name = "3.png"
          when "4"
            image_name = "4.png"
          when "5"
            image_name = "5.png"
          when "6"
            image_name = "6.png"
          when "7"
            image_name = "7.png"
          when "8"
            image_name = "8.png"
          when "9"
            image_name = "9.png"
          when "10"
            image_name = "10.png"
          when "11"
            image_name = "11.png"
          when "12"
            image_name = "12.png"
          when "X"
            image_name = "x.png"
        end
      end
      image_array << image_name unless image_name.empty?
    end
    image_array
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  # GET /cards
  # GET /cards.json
  before_filter :authenticate_user!, :except => [:show, :index]
  helper_method :sort_column, :sort_direction
  def index
    @cards = Card.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 15, :page =>params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cards }
    end
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @card = Card.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/new
  # GET /cards/new.json
  def new
    @card = Card.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/1/edit
  def edit
    @card = Card.find(params[:id])
  end

  # POST /cards
  # POST /cards.json
  def create
    handle_image_upload(params)
    @card = Card.new(params[:card])

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render json: @card, status: :created, location: @card }
      else
        format.html { render action: "new" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cards/1
  # PUT /cards/1.json
  def update
    handle_image_upload(params)
    @card = Card.find(params[:id])

    respond_to do |format|
      if @card.update_attributes(params[:card])
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card = Card.find(params[:id])
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end

  def sort_column
    Card.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
  private

  def handle_image_upload(params)
    if params[:card][:image]
      uploaded_io = params[:card][:image]
      File.open(Rails.root.join('app/assets','images','cards',uploaded_io.original_filename), 'wb') do |file|
        file.write(uploaded_io.read)
      end
      params[:card]['image'] = uploaded_io.original_filename
    end
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_cards.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<table class="table table-hover">
    <tr>
      <th><%= sortable "name" %></th>
      <th><%= sortable "cardset" %></th>
      <th><%= sortable "color" %></th>
      <th><%= sortable "manacost" %></th>
      <th><%= sortable "cardtype" %></th>
      <th><%= sortable "powertoughness","Power/Toughness" %></th>
      <th><%= sortable "price" %></th>
      <%	 if user_signed_in? %>
          <% if current_user.has_role? :admin %>
              <th></th>
              <th></th>
          <%end %>
      <%end %>

    </tr>

  <% @cards.each do |card| %>
      <tr>
        <td><%= link_to card.name, card %></td>
        <td><%= card.cardset %></td>
        <td>
          <% card.get_symbols(card.color).each do |cur_symbol| %>
              <%=	 image_tag "assortedimages/"+cur_symbol %>

          <% end %>
        </td>
        <td>
          <% card.get_symbols(card.manacost).each do |cur_symbol| %>
            <%=	 image_tag "assortedimages/"+cur_symbol %>

          <% end %>
        </td>
        <td><%= card.cardtype %></td>
        <td><%= card.powertoughness %></td>
        <td>
          <% if card.price.nil? %>
              <%= "**Price not entered**" %>
          <% else %>
              <%= number_to_currency(card.price) %>
          <% end %>
        </td>
        <%	 if user_signed_in? %>
            <% if current_user.has_role? :admin %>
             <td><%= link_to 'Edit', edit_card_path(card) %></td>
             <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <%end %>
        <%end %>
      </tr>
  <% end %>
</table>

app/views/cards/_form.html.erb
<%= simple_form_for @card, :html => {:multipart => true} do |f| %>
    <div class="darken-labels">
      <%= f.error_notification %>

        <div class="pull-left" style="margin:10px">
          <%= f.input :name, :as => :string %>
          <%= f.input :cardset, :as => :string %>
          <%= f.input :color, :as => :string %>
          <%= f.input :manacost, :as => :string %>
          <%= f.input :cardtype, :as => :string %>
          <%= f.input :powertoughness, :as => :string %>
        </div>
        <div class="pull-left" style="margin-top: 10px">
          <%= f.input :description, :as => :text %>
          <%= f.file_field :image %>
        </div>
        <div class="pull-left" style="margin:34px 10px 30px 20px">
          <%= image_tag "cards/" + @card.get_image %>
          <%= f.input :price, :as => :string%>
        </div>

      <div class="form-actions">
        <div class="pull-right" style="margin-top: 30px"><%= f.button :submit %></div>

      </div>
    </div>
<% end %>

app/views/cards/edit.html.erb
<h1 class="add-text-shadow"><%= image_tag "assortedimages/mtg_mana.png" %><span class="greenify">E</span>diting Card </h1>

  <div class="container_smaller">
    <div class="center">
      <%= link_to 'Show', @card %> |
      <%= link_to 'Back', cards_path %>
    </div>

    <div class="pull-left card-info">
        <%= render 'form' %>
    </div>

  <div class="clearfix"></div>

</div>

app/views/cards/index.html.erb
<div class="mtg-logo">
  <%= image_tag "assortedimages/mtg-logo.png" %>
</div>

<%= form_tag cards_path, :method => 'get', :id => "cards_search" do %>
    <div class="input-append pull-left negative_margin clearfix">
      <%= text_field_tag :search, params[:search] %>
      <%= button_tag "Search", :class => 'btn' %>
    </div>
    <div class="pull-right lessen-margin">
      <%= will_paginate @cards %>
    </div>
    <div class="clearfix"></div>
    <div id="cards" class="container"><%= render 'cards' %></div>
<% end %>
<% if user_signed_in? %>
<% if current_user.has_role? :admin %>
      <p><%= link_to 'New Card', new_card_path %></p>
<% end %>
<%	 end %>

app/views/cards/new.html.erb
<h1 class="add-text-shadow"><%= image_tag "assortedimages/mtg_mana.png" %><span class="greenify">N</span>ew Card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<div class="container clearfix" >
  <p id="notice"><%= notice %></p>
  <div class="container_smaller">
    <p>
      <% if user_signed_in? %>
          <% if current_user.has_role? :admin %>
            <%= link_to 'Edit', edit_card_path(@card) %> |
          <% end %>
      <% end %>
      <%= link_to 'Back To CardList', cards_path %>
    </p>

    <div class="pull-left card_image_area">
      <%= image_tag "cards/" + @card.get_image %>
    </div>
    <div class="pull-left card_content">
      <p>
        <b>Name:</b>
        <%= @card.name %>
      </p>

      <p>
        <b>Cardset:</b>
        <%= @card.cardset %>
      </p>

      <p>
        <b>Color:</b>
        <% @card.get_symbols(@card.color).each do |cur_symbol| %>
            <%=	 image_tag "assortedimages/"+cur_symbol %>
        <% end %>
      </p>
      <p>
        <b>Manacost:</b>
        <% @card.get_symbols(@card.manacost).each do |cur_symbol| %>
            <%=	 image_tag "assortedimages/"+cur_symbol %>
        <% end %>
      </p>
      <p>
        <b>Cardtype:</b>
        <%= @card.cardtype %>
      </p>

      <p>
        <b>Powertoughness:</b>
        <%= @card.powertoughness %>
      </p>
      <p>
        <b>Description:</b>
        <%= @card.description %>
      </p>
      <p>
        <b>Price:</b>
        <% if @card.price.nil? %>
            <%= "**Price not entered**" %>
        <% else %>
            <%= number_to_currency(@card.price) %>
        <% end %>

      </p>
    </div>
  </div>

</div>