config/routes.rb
Ccghoard::Application.routes.draw do

  resources :decks
  resources :cards

  authenticated :user do
    root :to => 'cards#index'
  end
  root :to => "cards#index"
  devise_for :users
  resources :users



end

app/models/deck.rb
class Deck < ActiveRecord::Base
  
  attr_accessible :name, :card_ids
  has_and_belongs_to_many :cards

  def deck_price
    total_cost = 0
    deck_cards = self.where(:deck_id => self.id)
    deck_cards do |c|
      total_cost+=c.price
    end
    total_cost
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  # GET /decks
  # GET /decks.json
  def index
    @decks = Deck.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @decks }
    end
  end

  # GET /decks/1
  # GET /decks/1.json
  def show
    @deck = Deck.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @deck }
    end
  end

  # GET /decks/new
  # GET /decks/new.json
  def new
    @deck = Deck.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @deck }
    end
  end

  # GET /decks/1/edit
  def edit
    @deck = Deck.find(params[:id])
  end

  # POST /decks
  # POST /decks.json
  def create
    @deck = Deck.new(params[:deck])

    respond_to do |format|
      if @deck.save
        format.html { redirect_to @deck, notice: 'Deck was successfully created.' }
        format.json { render json: @deck, status: :created, location: @deck }
      else
        format.html { render action: "new" }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /decks/1
  # PUT /decks/1.json
  def update
    @deck = Deck.find(params[:id])

    respond_to do |format|
      if @deck.update_attributes(params[:deck])
        format.html { redirect_to @deck, notice: 'Deck was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1
  # DELETE /decks/1.json
  def destroy
    @deck = Deck.find(params[:id])
    @deck.destroy

    respond_to do |format|
      format.html { redirect_to decks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/decks/_form.html.erb
<%= simple_form_for(@deck) do |f| %>
  <%= f.error_notification %>
    <div class="form-actions darken-labels">
  <div class="form-inputs">
    <%= f.input :name %>
    <%=f.association :cards, :as => :check_boxes %>
  </div>


    <%= f.button :submit %>
  </div>
<% end %>

app/views/decks/edit.html.erb
<h1>Editing deck</h1>

<%= render 'form' %>

<%= link_to 'Show', @deck %> |
<%= link_to 'Back', decks_path %>

app/views/decks/index.html.erb
<h1>Listing decks</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @decks.each do |deck| %>
  <tr>
    <td><%= deck.name %></td>
    <td><%= link_to 'Show', deck %></td>
    <td><%= link_to 'Edit', edit_deck_path(deck) %></td>
    <td><%= link_to 'Destroy', deck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Deck', new_deck_path %>

app/views/decks/new.html.erb
<h1>New deck</h1>

<%= render 'form' %>

<%= link_to 'Back', decks_path %>

app/views/decks/show.html.erb
<p id="notice"><%= notice %></p>

<h3><%=@deck.name%></h3>

<table class="table table-hover">
  <tr>
    <th>Name</th>
    <th>Cardset</th>
    <th>Color</th>
    <th>Manacost</th>
    <th>Cardtype</th>
    <th>Power/Toughness</th>
    <th>Price</th>

  </tr>
  <% total_cost = 0.0 %>
  <% cards = @deck.cards %>
  <% cards.each do |card| %>
      <% total_cost += card.price %>
      <tr>
        <td><%= link_to card.name, card %></td>
        <td><%= card.cardset %></td>
        <td>
          <% card.get_symbols(card.color).each do |cur_symbol| %>
              <%=	 image_tag "assortedimages/"+cur_symbol %>

          <% end %>
        </td>
        <td>
          <% card.get_symbols(card.manacost).each do |cur_symbol| %>
              <%=	 image_tag "assortedimages/"+cur_symbol %>

          <% end %>
        </td>
        <td><%= card.cardtype %></td>
        <td><%= card.powertoughness %></td>
        <td>
          <% if card.price.nil? %>
              <%= "**Price not entered**" %>
          <% else %>
              <%= number_to_currency(card.price) %>
          <% end %>
        </td>
        </tr>

  <% end %>
  <tr>
    <td colspan="7">Total Purchase Price: <%=	number_to_currency(total_cost) %></td>
  </tr>
</table>
<%= link_to 'Edit', edit_deck_path(@deck) %> |
<%= link_to 'Back', decks_path %>